# Generated by Django 4.1.5 on 2024-02-19 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='facts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landmark',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='landmark',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='landmark',
            name='pred_history',
            field=models.ManyToManyField(blank=True, related_name='predicted_landmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landmark',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_landmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
