# Generated by Django 4.1.5 on 2024-02-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='upload_data',
            new_name='upload_date',
        ),
    ]
