# Generated by Django 4.1.5 on 2024-02-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_landmark_facts_landmark_latitude_landmark_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='User', max_length=15),
        ),
    ]
